apiVersion: v1
kind: Secret
metadata:
  name: linebot-secret
type: Opaque  # 不透明
data: 
  LINE_CHANNEL_SECRET: NTlmOTc0YjliMmMzNTI0MjA2ODA1ZTgzYTZlYTBhODQ=
  LINE_CHANNEL_ACCESS_TOKEN: RVJFTG1BcWU0RHhYSk9jWVJmNFRSRkFoNVVqVWQvanUwQStuUjFmTHVIK25yZVcwYktRZEFWaWkxQnJsRGpTcTdOUWhIK1lsb1lVL2F6eW9wUjdCUEREK0IvcGNzWXZIV01wZWRhTlAzY2lTNHVvZlZRRFhhYW1KaXdlTEppQy9EbUdwQmZ5SlN1UTR4bTVJWlZKQ3VBZEIwNHQ4OS8xTy93MWNEbnlpbEZVPQ==