apiVersion: v1
kind: Service
metadata:
  name: im-line
spec:
  selector:
    app: im-line
  ports:
    - protocol: TCP
      port: 81
      targetPort: 5001
      nodePort: 30001      
  type: NodePort         
