apiVersion: v1
kind: ConfigMap
metadata:
  name: device-config
data:
  device_config.json: |
    {
        "esp32": {
            "url": "https://39016ad648ef.ngrok-free.app"
        },
        "raspberry_pi": {
            "url": "https://ba0d895cae58.ngrok-free.app"
        }
    }
