apiVersion: v1
kind: Secret
metadata:
  name: ecdsa-key-secret
type: Opaque
stringData:
  ecdsa_private.pem: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgGWY2ApudYuhTbegF
    AHxUHtHHApD2CCHTjEOBXL7KrFqhRANCAARtIV3NoyCwWUz+Sn1AaaXsbiH5HNT0
    sKDd1oazSw/SWupd2eRJ3UZ8tyLHXOnGFKrAaWHC1Wnsi1e9f8/XNfy7
    -----END PRIVATE KEY-----
  ecdsa_public.pem: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbSFdzaMgsFlM/kp9QGml7G4h+RzU
    9LCg3daGs0sP0lrqXdnkSd1GfLcix1zpxhSqwGlhwtVp7ItXvX/P1zX8uw==
    -----END PUBLIC KEY-----