apiVersion: v1
kind: Secret
metadata:
  name: ecdsa-key-secret
type: Opaque
stringData:
  ecdsa_private.pem: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgb2X09C5o/hWyc67ZyH8zeFpxQjorl0cL+pUFVQX5ALmhRANCAAR7XdaHSdjN2ayG8Cu/pAal9W3SQeq8GcBePx8SI5xgP6jWy/k6rmiojtQVQqXkznvW6I8CvMJTTErOIDjpFFT1
    -----END PRIVATE KEY-----
  ecdsa_public.pem: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEe13Wh0nYzdmshvArv6QGpfVt0kHqvBnAXj8fEiOcYD+o1sv5Oq5oqI7UFUKl5M571uiPArzCU0xKziA46RRU9Q==
    -----END PUBLIC KEY-----
