apiVersion: v1
kind: Service
metadata:
  name: iot-raspberrypi
spec:
  selector:
    app: iot-raspberrypi
  ports:
    - protocol: TCP
      port: 83
      targetPort: 5003
      nodePort: 30003    
  type: NodePort         
