apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    #log 用
    log_type all
    connection_messages true
    log_dest stdout

    # 允許匿名連線（測試用）
    allow_anonymous true  

    # 為 IoT 裝置建立 MQTT 監聽埠
    listener 1883 0.0.0.0
    protocol mqtt

    
