apiVersion: v1
kind: ConfigMap
metadata:
  name: device-config
data:
  device_config.json: |
    {
        "esp32": {
            "url": "https://141cd9fed071.ngrok-free.app"
        },
        "raspberry_pi": {
            "url": "https://860d21b8cb52.ngrok-free.app"
        }
    }
