apiVersion: v1
kind: ConfigMap
metadata:
  name: device-config
data:
  device_config.json: |
    {
        "esp32": {
            "url": "http://192.168.0.12:5010"
        },
        "raspberry_pi": {
            "url": "https://6f9c4a4eb1c6.ngrok-free.app"
        }
    }

