apiVersion: v1
kind: ConfigMap
metadata:
  name: device-config
data:
  device_config.json: |
    {
        "esp32": {
            "url": "https://60a602869159.ngrok-free.app/"
        },
        "raspberry_pi": {
            "url": "http://192.168.0.12:5011"
        }
    }

